<?php
function seed_couple(PDO $pdo,int $uid):void{
 $pdo->beginTransaction();try{
$s=$pdo->prepare("INSERT INTO couple_settings(id,names,start_date,first_met,about_text,final_message,updated_by) VALUES(1,'Sarah & Yuri','2026-07-16','2026-06-13',:a,'Nossa história só está começando ✨',:u) ON CONFLICT(id) DO NOTHING");$s->execute([':a'=>'Nossa história começou na Tribo, em 13/06/2026. Desde então, cada dia trouxe uma nova lembrança, um novo sorriso e mais um motivo para acreditar que as melhores histórias são escritas pouco a pouco. Eu poderia encher um livro inteiro dizendo o quanto você é importante para mim, mas talvez ele ficasse maior que um Vade Mecum. Então escolhi uma forma diferente de registrar tudo isso: este site. Aqui estão reunidos os momentos que marcaram nossa caminhada, transformados em páginas de uma retrospectiva feita com carinho, amor e gratidão. Espero que, ao percorrê-la, você sinta um pouco de tudo o que sinto por você e perceba que a nossa história é, sem dúvida, a mais bonita que eu poderia viver.',':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'Tribo',':o'=>'photo.jpg',':p'=>'images/photo.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>0,':l'=>'O início de tudo',':t'=>'Tribo',':d'=>'Em meio a tantas pessoas, Deus permitiu que nossos caminhos se encontrassem e que uma linda história começasse a ser escrita.',':i'=>$iid,':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'Gincana',':o'=>'photo1.jpg',':p'=>'images/photo1.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>1,':l'=>'Capítulo 1',':t'=>'Gincana',':d'=>'Foi na gincana que pudemos nos aproximar ainda mais. Eu não estava tão animado para participar, até perceber que seria uma oportunidade de nos vermos e conversarmos.',':i'=>$iid,':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'Primeiro encontro',':o'=>'photo2.jpg',':p'=>'images/photo2.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>2,':l'=>'Capítulo 2',':t'=>'Primeiro encontro',':d'=>'Passamos nosso primeiro final de semana inteiro juntos. Entre conversas, risadas e momentos simples, criamos lembranças que levaremos para sempre em nossos corações.',':i'=>$iid,':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'Passeando com a cara metade',':o'=>'photo3.jpg',':p'=>'images/photo3.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>3,':l'=>'Capítulo 3',':t'=>'Passeando com a cara metade',':d'=>'Descrições por Amore Mio/Sarah 😜',':i'=>$iid,':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'Final de semana juntos',':o'=>'photo4.jpg',':p'=>'images/photo4.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>4,':l'=>'Capítulo 4',':t'=>'Final de semana juntos',':d'=>'Descrições por Amore Mio/Sarah 😜',':i'=>$iid,':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'Cinema',':o'=>'photo5.jpg',':p'=>'images/photo5.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>5,':l'=>'Capítulo 5',':t'=>'Cinema',':d'=>'Ao lado da minha Mary Jane. Mas, diferente do Peter Parker, essa história não vai acabar. 😜❤️',':i'=>$iid,':u'=>$uid]);
$img=$pdo->prepare("INSERT INTO couple_images(display_name,original_name,mime_type,size_bytes,source_type,local_path,created_by,updated_by) VALUES(:n,:o,'image/jpeg',0,'local',:p,:u,:u) RETURNING id");$img->execute([':n'=>'TE AMO SARAH',':o'=>'photo6.jpg',':p'=>'images/photo6.jpg',':u'=>$uid]);$iid=(int)$img->fetchColumn();
$ch=$pdo->prepare("INSERT INTO couple_chapters(sort_order,chapter_label,title,description,image_id,created_by,updated_by) VALUES(:o,:l,:t,:d,:i,:u,:u)");$ch->execute([':o'=>6,':l'=>'Capítulo 6',':t'=>'TE AMO SARAH',':d'=>'Descrições por Amore Mio/Sarah 😜',':i'=>$iid,':u'=>$uid]);
$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}
}
